### PR TITLE
Add missing install targets

### PR DESCRIPTION
**Pull request by severin-lemaignan**

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
Thanks for this, we will be integrating it soon.

**Comment by reaganlo** [comment]
Severin, currently this code change causes a failure in our unit tests while sourcing the "devel" area because of the change in the package.xml file. Could you please update the pull request to move the "src/realsense_camera_nodelet_plugins.xml" from the "src" directory to the top level package directory (e.g at the same level as package.xml). So that the change works for both sourcing the "devel" or "install". Thanks.

**Comment by reaganlo** [comment]
Severin, we have incorporated your pull request, internally, and added my above mentioned fix. It will be part of our next release. Thanks for contributing.

**Comment by reaganlo** [comment]
Severin, we have incorporated your pull request, internally, and added my above mentioned fix. It is part of our Release 1.0.2.

Thanks for contributing.

**Pull request closed without merging**
