### PR TITLE
Address cameras by serial number and support running multiple concurr…

### PR DESCRIPTION
**Pull request by liz-murphy**
…ent processes

Addresses #7

### CODE REVIEW

**Comment by liz-murphy** [comment]
I see a lot of this error and often only one process starts up successfully:

[ERROR] [1457594957.962800200]: RealSense Camera - Error calling rs_create_context ( api_version:4 ): 
UVCIOC_CTRL_QUERY:UVC_SET_CUR error 5, Input/output error

**Comment by reaganlo** [comment]
@liz-murphy The pull request is giving compilation errors; so I am not able to test it. Could you please look into it.

**Comment by reaganlo** [comment]
@liz-murphy 
I am **assuming** that you are getting the "UVCIOC_CTRL_QUERY:UVC_SET_CUR error 5" while using **multiple cameras**. Our current code does not support multiple cameras. We have this requirement in our backlog. So with multiple cameras, you may come across errors like "UVCIOC_CTRL_QUERY:UVC_SET_CUR error 2" and "UVCIOC_CTRL_QUERY:UVC_SET_CUR error 5". Even the librealsense examples (cpp-capture) would give the similar errors with multiple cameras connected.

But you **should not** be getting this error with a **single camera**. If yes, I would suggest running the librealsense example (cpp-capture). If you get the same error with the librealsense example too, then it could be either:
- The camera firmware is not updated. The latest stable firmware version is **1.0.72.06**. To update the firmware you will need to download and run this [executable](https://downloadmirror.intel.com/25044/eng/intel_rs_dcm_r200_2.1.24.6664.exe) on a windows machine with the camera connected to a USB 3.0 port. OR
- The uvc driver patches were not applied correctly. Refer to the [README](https://github.com/intel-ros/realsense/blob/indigo-devel/camera/README.md#installation) for installation steps.

Hope this helps.

**Comment by reaganlo** [comment]
@liz-murphy , FYI I have created an Issue for the enabling ros params at https://github.com/intel-ros/realsense/issues/11

**Pull request closed without merging**
