### PR TITLE
Kinetic devel

### PR DESCRIPTION
**Pull request by jgoppert**
Please create new kinetic-devel branch for this PR.

Changes proposed in this pull request:
- Changes for ubuntu 16.04 build/ ros kinetic
- Adds librealsense wrapper to simplify build procedure.
- Tested. Depth/ ir and rgb working without any kernel modification or patching.

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
Thanks for submitting. We're discussing internally how to proceed and will get back to you.

**Comment by jgoppert** [comment]
@mkhansen-intel Great, let me know if you need anything from me.  I left a lot of boiler plate in there assuming you guys would replace the maintainer etc. with your own info. I think having the librealsense wrapper makes it easier to get people up an running quickly and really becomes more reasonable in kinetic where you don't have to go through all of the kernel patching and custom config to get it running on your system.

**Comment by v4hn** [comment]
Hey guys,

having librealsense released with the ROS ecosystem probably makes sense until it is stable enough to be included with distributions like debian directly.
However, this should follow the ROS REP for that: http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty
So :-1: on this request.

Given that both intel-ros/realsense and IntelRealSense/librealsense are official Intel projects it might be possible to take the very easy road to add a package.xml file to the librealsense project. (see REP)

**Comment by jgoppert** [comment]
@v4hn, agree

**Comment by mdhorn** [comment]
@v4hn Maybe I'm missing something, but I don't see how to test the package.xml file I created for the librealsense in a prerelease environment.
http://wiki.ros.org/bloom/Tutorials/PrereleaseTest
Or in general, how to test in prelease if the package has never been release before.

**Comment by v4hn** [comment]
See http://answers.ros.org/question/201954/prerelease-tests-with-bloom-on-first-release/ .
Pre-release tests are not that helpful for new packages because there are no dependent packages to test.

I would simply build it locally as part of an install workspace and see if everything installed correctly.

**Comment by mdhorn** [comment]
In progress...

**Comment by mdhorn** [comment]
Currently working to release librealsense as a ROS package.
Once it is available, we will enable the package dependency and release realsense_camera as a ROS package.

Closing this PR as it will not be merged.

**Pull request closed without merging**
